name: Deploy Frontend to Azure Storage

on:
  push:
    branches: [ main ]
    paths:
      - 'Frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Upload to Blob Storage
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name melvincloudresume \
              --auth-mode key \
              --account-key ${{ secrets.AZURE_STORAGE_KEY }} \
              -d '$web' \
              -s ./Frontend \
              --overwrite
